### ISSUE TITLE
Only works up to 3 images

### ISSUE THREAD

**Issue by NeonVolta** [Tanza3D/discord-no-mosaic#1]
the css only seems to work up to 3 images, anything between 4 and 10 images in a single message still causes mosaic

![image](https://user-images.githubusercontent.com/75271897/220489291-a94bc817-21e1-47f8-bfd4-bffa8c9842c9.png)

**Comment by Tanza3D** [comment]
sorry about that, only tested up to three! i've made some changes tested all the way up to 10 now and it's working flawlessly now
