### ISSUE TITLE
Vertical-shaped images are zoomed in

### ISSUE THREAD

**Issue by Kiki79250CoC** [Tanza3D/discord-no-mosaic#2]
I downloaded your solution to the image mosaic mess and after scrolling into my archive server channels, I realized that some images are still zoomed in (especially long images).

![image](https://user-images.githubusercontent.com/54137141/220681964-ad2c8294-f985-49fa-954b-1090abda4aba.png)

The first two images are displaying correctly, but the two others which are vertical, are zoomed.

Image 1 : 16:9 - 1280x720px
Image 2 : Wide - 3000x393px
Image 3 : Portrait 9:16 - 1080x1920px
Image 4 : Extra high vertical image : 1080x6000px

**Comment by Tanza3D** [comment]
oop, i see, i'll see if i can get to that today or tomorrow

**Comment by Tanza3D** [comment]
fixed!
