### ISSUE TITLE
2 image post problems

### ISSUE THREAD

**Issue by Scrooge200FES** [Tanza3D/discord-no-mosaic#3]
I have a problem with posting two images in the same message. They both get really squished to a 1:1 aspect ratio, cutting off a lot of the image.

**Comment by Tanza3D** [comment]
can you send the image?

**Comment by Scrooge200FES** [comment]
Any widescreen image will work. For example, try posting this twice in the same message; you can see the text get cut off.
![srtc](https://user-images.githubusercontent.com/88919077/222858521-4f35fa31-314b-4db3-8061-d8f2f1304515.png)

**Comment by Tanza3D** [comment]
ah, discord must have changed something, i just saw the issue myself. will fix tomorrow

**Comment by Tanza3D** [comment]
well, bad news, turns out discord's changed the way images embed so it auto-crops the image to begin with
![image](https://user-images.githubusercontent.com/33783503/222895213-50bc3a1a-be0f-4516-ab0e-3ec65ccf1f18.png)
i guess js time

**Comment by Tanza3D** [comment]
fixed! use this JS plugin now: https://github.com/Tanza3D/discord-no-mosaic/blob/main/nomoasic.plugin.js

**Comment by Aridow** [comment]
I have the same issue but only with gifs.
