### ISSUE TITLE
Seemingly no longer works (at least with cropping)

### ISSUE THREAD

**Issue by AManNamed2** [Tanza3D/discord-no-mosaic#4]
Updated BD today, and suddenly I'm back to cropped images. They're still loaded vertically loaded which is nice but I can't for the life of me figure out what exactly is cropping them now
![image](https://user-images.githubusercontent.com/50536667/222828837-139b953e-02c1-408b-b192-b4d40d05e25d.png)

**Comment by Tanza3D** [comment]
yep, known #3

**Comment by Tanza3D** [comment]
fixed with js plugin https://github.com/Tanza3D/discord-no-mosaic/blob/main/nomoasic.plugin.js

**Comment by Tanza3D** [comment]
for your info, it was being cropped serverside, luckily just with a query which i can remove through JS :3
